Vagrant.configure("2") do |config|

  config.vm.box = "centos/8"

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end

  config.vm.define "server" do |server|
    server.vm.network "private_network", ip: "192.168.56.100"
    server.vm.hostname = "server"
    server.vm.provision "file", source:"./compose/monitoring-compose.yml", destination: "/home/vagrant/monitoring-compose.yml"
    server.vm.provision "file", source:"./compose/wiki-compose.yml", destination: "/home/vagrant/wiki-compose.yml"
    server.vm.provision "shell", path:"./compose/server.sh"
  end
  
    (1..2).each do |i|
    config.vm.define "client-#{i}" do |clients|
      clients.vm.box = "centos/8"
      clients.vm.network "private_network", ip: "192.168.56.11#{i}"
      clients.vm.hostname = "client-#{i}"
      clients.vm.provision "shell", path:"./compose/client.sh"
    end
  end
end