Vagrant.configure("2") do |config|

  config.vm.box = "centos/8"

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end

  config.vm.define "server" do |server|
    server.vm.network "private_network", ip: "192.168.56.100"
    server.vm.hostname = "server"
    server.vm.provision "file", source:"./compose/monitoring-compose.yml", destination: "/home/vagrant/monitoring-compose.yml"
    server.vm.provision "file", source:"./compose/wiki-compose.yml", destination: "/home/vagrant/wiki-compose.yml"
    server.vm.provision "shell", path:"./compose/server.sh"
  end
  
  (1..2).each do |i|
    config.vm.define "client-#{i}" do |clients|
      clients.vm.box = "centos/8"
      clients.vm.network "private_network", ip: "192.168.56.11#{i}"
      clients.vm.hostname = "client-#{i}"
      clients.vm.provision "shell", path:"./compose/client.sh"
      clients.vm.provision "shell", inline: <<-SHELL
    
      cd /etc/netdata
      cat netdata.conf  | awk '$0=="[backend]" {iamin="yes"} ; $0=="" {iamin="no"} ; iamin=="yes" && $2=="type" {print "        "$2" "$3" opentsdb"} iamin=="yes" && $2!="type" {print $0} ; iamin!="yes" {print $0} ' | awk '$0=="[backend]" {iamin="yes"} ; $0=="" {iamin="no"} ; iamin=="yes" && $2=="enabled" {print "        "$2" "$3" yes"} iamin=="yes" && $2!="enabled" {print $0} ; iamin!="yes" {print $0} ' | awk '$0=="[backend]" {iamin="yes"} ; $0=="" {iamin="no"} ; iamin=="yes" && $2=="destination" {print "        "$2" "$3" 192.168.56.100:4242"} iamin=="yes" && $2!="destination" {print $0} ; iamin!="yes" {print $0} ' > toto
      mv netdata.conf netdata.orig
      mv toto netdata.conf

      SHELL
    end
  end
end