version: '3'
services:

  prometheus:
    image: prom/prometheus:v2.1.0
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/var/lib/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      grafana:
        aliases:
          - prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    user: '0'
    links:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      grafana:
        aliases:
          - grafana

  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki.yml:/etc/loki/loki.yml
      - loki-data:/var/lib/loki
    command: 
    - '--config.file=/etc/loki/loki.yml'
    networks:
      grafana:
          aliases:
            - loki

  promtail:
    image: grafana/promtail
    ports:
      - "9080:9080"
    volumes:
      - ./promtail.yml:/etc/promtail/promtail.yml
      - /var/log:/var/log
    command: 
      - '--config.file=/etc/promtail/promtail.yml'
    networks:
      grafana:
          aliases:
            - promtail


volumes:
  grafana-data:
  prometheus-data:
  loki-data:


networks:
  grafana: