version: '3'
services:

  dbpostgre:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      wikijs:
        aliases:
          - db

  wiki:
    image: requarks/wiki:2
    depends_on:
      - dbpostgre
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    ports:
      - '8080:3000'
    networks:
      wikijs:
        aliases:
          - wikijs

volumes:
  db-data:

networks:
  wikijs: